# Child pipeline du service "users"
# Utilise les modèles de pipeline pour les tâches Docker et le déploiement

# Variables définies par l'appelant
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   HOSTPORT:       port exposé sur l'hôte pour accéder au service via Docker
#   CONTAINERPORT:  port exposé dans le conteneur Docker
#   URL_PATH:       chemin URL pour vérifier que le service est bien démarré (ex: "api/v1/health")
#   CHART_DIR:      repertoire contenant les fichiers du Chart Helm
#   DEPLOY_NAME:    nom de déploiment Helm (release name) du mciro-service
#   HOSTNAME:       nom d'hôte utilisé pour générer le FQDN du service (ex: api, dashboard, smtp)
#   DOMAIN:         domaine où déployer le service (ex: dev.mondomaine.com)
#


include:
  - local: '.gitlab/ci/templates/var-precheck-template.yml'
  - local: '.gitlab/ci/templates/build-template.yml'


variables:
  # TAG: $TAG
  HOSTPORT: 7080
  CONTAINERPORT: "80"
  URL_PATH: ""
  IMAGENAME: frontend


stages:
  - pre_checks  # importé
  - build       # importé
  - run         # importé
  - push        # importé


upstream_var_checks:
  extends: .var_checks_template
  variables:
    REQUIRED_VARS: "IMAGENAME IMAGETAG HOSTPORT CONTAINERPORT CHART_DIR DEPLOY_DOMAIN"


# ----------------------------------------------
# Variables pour le job 'run' du template inclus
# ----------------------------------------------
run_image:

  