# Child pipeline du Chaert "Frontend"

# Variables définies par l'appelant
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   NAMESPACE:      namespace Kubernetes (par exemple, dev, qa, staging, prod)
#   CHART_DIR:      repertoire contenant les fichiers du Chart Helm
#   DEPLOY_NAME:    nom de déploiment Helm (release name) du mciro-service
#   HOSTNAME:       nom d'hôte utilisé pour générer le FQDN du service (ex: api, dashboard, smtp)
#   DOMAIN:         domaine utilisé pour accéder au service (ex: app.dev.mondomaine.com)
#   URL_PATH:       chemin URL pour accéder au service (ex: "api/v1/health")
#
#   ENV_NAME:       Nom de l'environnement (par exemple, dev/feature-branch, qa/main, staging/main, prod/main)
#                   Doit être unique pour chaque job de déploiement (surcharger le job dans l'appelant))


include:
  - local: '.gitlab/ci/var-precheck-template.yml'
  # - local: '.gitlab/ci/helm-deploy-template.yml'


stages:
  - pre_checks  # importé
  - deploy
  # - deploy_dev
  # - deploy_qa
  # - deploy_staging
  - deploy_prod


# ----------------------------------------------
# Stage 'pre_checks' importé du template
# ----------------------------------------------
upstream_var_checks:
  extends: .var_checks_template
  variables:
    REQUIRED_VARS: "IMAGENAME TAG NAMESPACE CHART_DIR DEPLOY_NAME HOSTNAME DOMAIN URL_PATH ENV_NAME"


# ----------------------------------------------
# Deploiement sur DEV
# ----------------------------------------------
deploy_dev:
  stage: deploy
  trigger:
    include: ".gitlab/ci/helm-deploy-template.yml"
    strategy: depend
  variables:
    ENV_NAME: dev/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $TAG
    NAMESPACE: dev
    CHART_DIR: $CHART_DIR
    DEPLOY_NAME: $DEPLOY_NAME
    HOSTNAME: $HOSTNAME
    DEPLOY_DOMAIN: dev.$DOMAIN
    URL_PATH: ""
    OPTIONAL_ARG: ""


# ----------------------------------------------
# Quality Assurance
# ----------------------------------------------
deploy_qa:
  stage: deploy
  trigger:
    include: ".gitlab/ci/helm-deploy-template.yml"
    strategy: depend
  variables:
    ENV_NAME: qa/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $TAG
    NAMESPACE: qa
    CHART_DIR: $CHART_DIR
    DEPLOY_NAME: $DEPLOY_NAME
    HOSTNAME: $HOSTNAME
    DEPLOY_DOMAIN: qa.$DOMAIN
    URL_PATH: ""
    OPTIONAL_ARG: ""


# ----------------------------------------------
# STAGING
# ----------------------------------------------
deploy_staging:
  stage: deploy
  trigger:
    include: ".gitlab/ci/helm-deploy-template.yml"
    strategy: depend
  variables:
    ENV_NAME: staging/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $TAG
    NAMESPACE: staging
    CHART_DIR: $CHART_DIR
    DEPLOY_NAME: $DEPLOY_NAME
    HOSTNAME: $HOSTNAME
    DEPLOY_DOMAIN: staging.$DOMAIN
    URL_PATH: ""
    OPTIONAL_ARG: ""


# ----------------------------------------------
# PRODUCTION
# ----------------------------------------------
deploy_prod:
  stage: deploy_prod
  trigger:
    include: ".gitlab/ci/helm-deploy-template.yml"
    strategy: depend
  when: manual
  only:
    - main
  variables:
    ENV_NAME: prod/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $TAG
    NAMESPACE: prod
    CHART_DIR: $CHART_DIR
    DEPLOY_NAME: $DEPLOY_NAME
    HOSTNAME: $HOSTNAME
    DEPLOY_DOMAIN: prod.$DOMAIN
    URL_PATH: ""
    OPTIONAL_ARG: ""
