# Child pipeline du service "users"
# Utilise les modèles de pipeline pour les tâches Docker et le déploiement

# Variables définies par l'appelant
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   HOSTPORT:       port exposé sur l'hôte pour accéder au service via Docker
#   CONTAINERPORT:  port exposé dans le conteneur Docker
#   URL_PATH:       chemin URL pour vérifier que le service est bien démarré (ex: "api/v1/health")
#   CHART_DIR:      repertoire contenant les fichiers du Chart Helm
#   DEPLOY_NAME:    nom de déploiment Helm (release name) du mciro-service
#   HOSTNAME:       nom d'hôte utilisé pour générer le FQDN du service (ex: api, dashboard, smtp)
#   DOMAIN:         domaine où déployer le service (ex: dev.mondomaine.com)
#


include:
  - local: '.gitlab/ci/var-precheck-template.yml'
  - local: '.gitlab/ci/helm-deploy-template.yml'

stages:
  - pre_checks  # importé
  - deploy
  # - deploy_dev
  # - deploy_qa
  # - deploy_staging
  - deploy_prod


# ----------------------------------------------
# Deploiement sur DEV
# ----------------------------------------------
deploy_dev:
  stage: deploy
  trigger:
    # downstream pipeline
    include: "ci-templates/.ci-deploy-pipeline-template.yml"
    strategy: depend
  variables:
    # downstream variable
    ENV_NAME: dev/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $IMAGETAG
    NAMESPACE: dev
    DEPLOY_DOMAIN: dev.$DOMAIN
    # CHART_DIR: $CHART_DIR
    # URL_PATH: ""  


# ----------------------------------------------
# Quality Assurance
# ----------------------------------------------
deploy_qa:
  stage: deploy
  trigger:
    # downstream pipeline
    include: "ci-templates/.ci-deploy-pipeline-template.yml"
    strategy: depend
  variables:
    # downstream variable
    ENV_NAME: qa/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $IMAGETAG
    NAMESPACE: qa
    DEPLOY_DOMAIN: qa.$DOMAIN


# ----------------------------------------------
# STAGING
# ----------------------------------------------
deploy_staging:
  stage: deploy
  trigger:
    # downstream pipeline
    include: "ci-templates/.ci-deploy-pipeline-template.yml"
    strategy: depend
  variables:
    # downstream variable
    # downstream variable
    ENV_NAME: staging/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $IMAGETAG
    NAMESPACE: staging
    DEPLOY_DOMAIN: staging.$DOMAIN


# ----------------------------------------------
# PRODUCTION
# ----------------------------------------------
deploy_prod:
  stage: deploy_prod
  trigger:
    # downstream pipeline
    include: "ci-templates/.ci-deploy-pipeline-template.yml"
    strategy: depend
  when: manual
  only:
    - main
  variables:
    # downstream variable
    ENV_NAME: prod/$CI_COMMIT_REF_NAME
    IMAGENAME: $IMAGENAME
    TAG: $IMAGETAG
    NAMESPACE: prod
    DEPLOY_DOMAIN: $DOMAIN
  