# Modèle de pipeline Docker
# Organise les 3 étapes : build, run et push

# -------------------------------------------------------------------------------------------
# Upstream variables, devant être définies dans le job appelant
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   HOSTPORT:       port exposé sur l'hôte pour accéder au service via Docker
#   CONTAINERPORT:  port exposé dans le container Docker
#   URL_PATH:       URL path pour vérifier que le service est bien démarré (ex: "api/v1/health")
# -------------------------------------------------------------------------------------------

include:
  - local: '.gitlab/ci/templates/var-precheck-template.yml'
  - template: 'Jobs/Container-Scanning.gitlab-ci.yml'
  - template: 'Jobs/SAST.gitlab-ci.yml'


stages:
  - pre_checks
  - build
  - run
  - push
  - test


# variables:      # Déplacé dans le Worflow pour appication conditionnelle.
#   DOCKER_TLS_CERTDIR: "/certs"
#   DOCKER_TLS_VERIFY: 1
#   DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"


default:
  tags:
    - ${EXECUTION_MODE}-executor

# ----------------------------------------------
# Stage 'pre_checks' importé du template
# ----------------------------------------------
upstream_var_checks:
  stage: pre_checks
  image: ubuntu:24.04
  extends: .var_checks_template
  variables:
    REQUIRED_VARS: "IMAGENAME TAG HOSTPORT CONTAINERPORT URL_PATH"


#----------------------------------------------
# Construire l'image Docker et la taguer (compatible Shell et Docker)
#----------------------------------------------
build_run_push:
  stage: build
  image: docker:cli
  services:
    - docker:dind

  before_script:
    # s'identifier auprès du registre privé GitLab avant le Push
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    
    # si docker-executor, ajouter curl à l'image DinD
    - |
      if [ "$EXECUTION_MODE" = "docker" ]; then
        echo "Installing curl (Docker executor mode)"
        apk add --no-cache curl
      else
        echo "Skipping curl installation (Shell executor mode)"
      fi

  script:
    # Build
    - |
      TAG="${TAG:-tag-not-found}" 
      echo "Building with tag: $TAG"
      
      IMAGE="$CI_REGISTRY_IMAGE/$IMAGENAME:$TAG"
      
      docker build -t "$IMAGE" ./$IMAGENAME
      
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$IMAGE" "$CI_REGISTRY_IMAGE/$IMAGENAME:latest"
        docker tag "$IMAGE" "$CI_REGISTRY_IMAGE/$IMAGENAME:$CI_COMMIT_TAG"
      fi
    
    # Run
    - |
      echo echo "Running container for validation..."
      echo "Image: $IMAGE"
      echo "Hostport: $HOSTPORT"
      echo "Containerport: $CONTAINERPORT"

      if [ "$EXECUTION_MODE" = "docker" ]; then        
        URL="http://docker:${HOSTPORT}${URL_PATH}"

      else
        docker stop $IMAGENAME || true
        docker rm $IMAGENAME || true

        URL="http://localhost:${HOSTPORT}${URL_PATH}"
      
      fi

      echo "Starting container..."
      docker run --env-file .env -d -p $HOSTPORT:$CONTAINERPORT --name "$IMAGENAME" "$IMAGE" || exit 1

      echo "Checking container is responding..."
      SUCCESS=false

      for i in $(seq 1 30); do
        if curl -sf -o /dev/null -w "├─ HTTP Code %{http_code}\n" "${URL}"; then
          SUCCESS=true
          break
        fi
        sleep 3
      done

      if [ "$SUCCESS" != "true" ]; then
        echo "└─ ERROR: service unreachable after 30 attempts"
        exit 1
      fi
  
      echo "└─ Container is healthy"
      docker stop $IMAGENAME || true
      docker rm $IMAGENAME || true

    # Push
    - |
      echo "Pushing $IMAGENAME to registry"
      docker push "$IMAGE"
    
    # Push également le tag 'latest' si le tag Git du commit est défini
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        echo "Release TAG detected: pushing tags '$CI_COMMIT_TAG' and 'latest'"
        docker push "$CI_REGISTRY_IMAGE/$IMAGENAME:latest"
        docker push "$CI_REGISTRY_IMAGE/$IMAGENAME:$CI_COMMIT_TAG"
      fi


container_scanning:
  rules:
    - if: '$EXECUTION_MODE == "docker"'
  tags:
    - docker-executor
  variables:
    CS_IMAGE: $CI_REGISTRY_IMAGE/$IMAGENAME:$TAG
