# Modèle de pipeline Docker utilisant des jobs réutilisables
# Organise les 3 étapes : build, run et push

##### Upstream variables ##### 
# Les variables suivantes doivent être définies ici OU dans l'appelant
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   HOSTPORT:       port exposé sur l'hôte pour accéder au service via Docker
#   CONTAINERPORT:  port exposé dans le container Docker
#   URL_PATH:       URL path pour vérifier que le service est bien démarré (ex: "api/v1/healthz")
#


stages:
  - build
  - run
  - push


#----------------------------------------------
# Construire l'image Docker et la taguer
#----------------------------------------------
build_image:
  stage: build
  script:
    - TAG="${TAG:-manual-test}"   # fallback - si TAG est vide alors le déclenchement ne vient pas d'un commit et est manuel, donc affecter une valeur à TAG
    - echo "Building with tag: $TAG"
    - cd $IMAGENAME/
    - docker build -t "$CI_REGISTRY_IMAGE/$IMAGENAME:$TAG" .
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$CI_REGISTRY_IMAGE/$IMAGENAME:$TAG" "$CI_REGISTRY_IMAGE/$IMAGENAME:latest"
        docker tag "$CI_REGISTRY_IMAGE/$IMAGENAME:$TAG" "$CI_REGISTRY_IMAGE/$IMAGENAME:$CI_COMMIT_TAG"
      fi


# ----------------------------------------------
# Exécuter le container et vérifier qu'il répond
# ----------------------------------------------
run_image:
  stage: run
  script:
    - TAG="${TAG:-manual-test}"  # fallback manuel
    - echo "Running with tag: $TAG"
    - docker run -d -p $HOSTPORT:$CONTAINERPORT --name $IMAGENAME "$CI_REGISTRY_IMAGE/$IMAGENAME:$TAG"
    - sleep 5
    - curl -sf -o /dev/null -w "HTTP Code':' %{http_code}\n" http://localhost:$HOSTPORT/$URL_PATH
  after_script:
    - docker stop $IMAGENAME || true
    - docker rm $IMAGENAME || true


# ----------------------------------------------
# Pousser l'image Docker vers le registre
# ----------------------------------------------
push_image:
  stage: push
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - TAG="${TAG:-manual-test}"  # fallback manuel
    - echo "Pushing tag: $TAG"
    - docker push "$CI_REGISTRY_IMAGE/$IMAGENAME:$TAG"
    # Push également le tag 'latest' si le tag Git du commit est défini
    - |
      if [ ! -z "$CI_COMMIT_TAG" ]; then
        echo "Release TAG detected: pushing tags '$CI_COMMIT_TAG' and 'latest'"
        docker push "$CI_REGISTRY_IMAGE/$IMAGENAME:latest"
        docker push "$CI_REGISTRY_IMAGE/$IMAGENAME:$CI_COMMIT_TAG"
      fi

