# Modèle de pipeline de déploiement utilisant des jobs réutilisables
# Organise le déploiement dans les environnements : dev, qa, staging, prod

# Les variables suivantes doivent être définies par le pipeline appelant (ou son parent)
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   NAMESPACE:      namespace Kubernetes (par exemple, dev, qa, staging, prod)
#   CHART_DIR:      repertoire contenant les fichiers du Chart Helm
#   DEPLOY_NAME:    nom de déploiment Helm (release name) du mciro-service
#   HOSTNAME:       nom d'hôte utilisé pour générer le FQDN du service (ex: api, dashboard, smtp)
#   DEPLOY_DOMAIN:  domaine utilisé pour accéder au service (ex: app.dev.mondomaine.com)
#   URL_PATH:       chemin URL pour accéder au service (ex: "api/v1/health")
#
#   ENV_NAME:       Nom de l'environnement (par exemple, dev/feature-branch, qa/main, staging/main, prod/main)
#                   Doit être unique pour chaque job de déploiement (surcharger le job dans l'appelant))


stages:
  - deploy


# ----------------------------------------------
# Déploiement de la release Helm
# ----------------------------------------------
helm_deploy:
  stage: deploy
  environment:
    on_stop: stop_deploy
    name: $ENV_NAME
    url: http://$HOSTNAME.$DEPLOY_DOMAIN/$URL_PATH
  variables:
    ENV_NAME: $ENV_NAME
  before_script:
    - echo "ENV_NAME=$ENV_NAME"
    - echo "NAMESPACE=$NAMESPACE"
    - echo "DEPLOY_NAME=$DEPLOY_NAME"
    - echo "CHART_DIR=$CHART_DIR"
    - echo "TAG=$TAG"
    - echo "URL" http://$HOSTNAME.$DEPLOY_DOMAIN/$URL_PATH
  script:
    - |
      OPTIONAL_ARG=""
    #   if [ "$SERVICE_TYPE" = "NodePort" ]; then
    #     OPTIONAL_ARG="--set service.nodePort=$NODEPORT"
    #   fi
    - >
      sudo helm upgrade --install $DEPLOY_NAME $CHART_DIR
      --values=$CHART_DIR/values.yaml
      --values=values-$NAMESPACE.yaml
      --namespace $NAMESPACE --create-namespace
      --set domain="$DEPLOY_DOMAIN"
      --set image.repository="$CI_REGISTRY_IMAGE/$IMAGENAME"
      --set image.tag="$TAG"
      --set nameOverride="$HOSTNAME"
      $OPTIONAL_ARG


# ----------------------------------------------
# Stop (désinstaller la release Helm)
# ----------------------------------------------
stop_helm_deploy:
  stage: deploy
  when: manual
  environment:
    name: $ENV_NAME
    action: stop
  script:
    - sudo helm uninstall $DEPLOY_NAME -n $NAMESPACE
