# Pipeline principal - Orchestrateur des pipelines enfants (propres à chaque image)
include:
  - template: 'Jobs/SAST.gitlab-ci.yml'


variables:
  TAG: $CI_COMMIT_SHORT_SHA
  CHARTS_DIR: Helm
  DEPLOY_PROJECT: projet_fastapi_deploy
  FF_SCRIPT_SECTIONS: "true"

  MANUAL_MODE: false  # Permettre le déclenchement manuel des jobs (utile en test)
  PIPELINE_NAME: "App build pipeline"
  EXECUTION_MODE: "docker"  # docker / shell
  ENABLE_SAST: "true"


# utlisation d'un Workflow pour ajuster les variables selon le type de Runner voulu
workflow:
  name: '$PIPELINE_NAME'
  rules:
    # Push avec changements du code source
    - if: '$CI_PIPELINE_SOURCE == "push"'
      changes:
        - frontend/**/*
        - backend/**/*
      variables:
        PIPELINE_NAME: 'Updated source code on $CI_COMMIT_REF_NAME: commit $CI_COMMIT_SHORT_SHA'
    
    # Push avec changements des outils optionels du cluster
    - if: '$CI_PIPELINE_SOURCE == "push"'
      variables:
        PIPELINE_NAME: 'Updated CI code'

    # Merge Request
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
      variables:
        PIPELINE_NAME: 'MR pipeline: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
    
    # Déclenchement manuel via Web UI: Passer tous les déploiements en manuel car aucun push pour évaluer les conditions 'changes'
    - if: '$CI_PIPELINE_SOURCE == "web"'
      variables:
        PIPELINE_NAME: 'Manual pipeline on $CI_COMMIT_REF_NAME'
        MANUAL_MODE: true

    # Bloqué dans tout autre cas
    - when: always


stages:
  - test  # Scan du code source (SAST)
  - backend_build
  - frontend_build


# Job Tags par défaut basé sur la variable $EXECUTION_MODE
# Influence le choix du Runner par le tag : Shell ou Docker
# Les runners doivent être tagués correctement 'shell-executor' ou 'docker-executor'
default:
  tags:
    - ${EXECUTION_MODE}-executor


# ----------------------------------------------
# SAST code Scanning
# ----------------------------------------------

semgrep-sast:
  rules:
    - if: '$EXECUTION_MODE == "docker" && $ENABLE_SAST == "true"'
  tags:
    - docker-executor


# ----------------------------------------------
# Job Rules Templates
# ----------------------------------------------

.job_rules:
  rules:
    # déclencher si les fichiers du dossiers changent (matche aussi sur trigger, sans git diff)
    - if: '$CI_PIPELINE_SOURCE =~ /^(push|merge_request_event)$/'
      changes:
        - $IMAGENAME/*
        - $IMAGENAME/**/*
    # fallback de déclenchement manuel si activé
    - if: '$MANUAL_MODE =~ /^(1|true|yes)$/'
      when: manual
    # sinon, ne jamais déclencher
    - when: never


# ----------------------------------------------
# Trigger Build, Run, Push child
# ----------------------------------------------

frontend:
  stage: frontend_build
  extends: .job_rules
  trigger:
    include: ".gitlab/ci/templates/build-template-dind.yml"
    strategy: depend
  variables:
    # vérifie la valeur des variables et échoue si absentes. Vide ou "disabled" pour annuler le check.
    ENABLE_PRECHECK: false
    REQUIRED_VARS: "EXECUTION_MODE IMAGENAME TAG HOSTPORT CONTAINERPORT URL_PATH"
    IMAGENAME: frontend
    HOSTPORT: 6080
    CONTAINERPORT: 80
    URL_PATH: "/"


backend:
  stage: backend_build
  extends: .job_rules
  trigger:
    include: ".gitlab/ci/templates/build-template-dind.yml"    # .gitlab/ci/templates/build-template.yml
    strategy: depend
  variables:
    # vérifie la valeur des variables et échoue si absente. Vide ou "disabled" pour annuler le check.
    ENABLE_PRECHECK: false
    REQUIRED_VARS: "EXECUTION_MODE IMAGENAME TAG HOSTPORT CONTAINERPORT URL_PATH"    
    IMAGENAME: backend
    HOSTPORT: 7800
    CONTAINERPORT: 8000
    URL_PATH: "/api/v1/utils/health-check/"


# ----------------------------------------------
# Les images pushées sont detecteées par Kargo
# Kargo organise ensuite la configuration de Deploiement et déclenche le pipeline
# ----------------------------------------------
