# Pipeline principal - Orchestrateur des pipelines enfants (propres à chaque image)
include:
  - template: 'Jobs/SAST.gitlab-ci.yml'


variables:
  TAG: $CI_COMMIT_SHORT_SHA
  CHARTS_DIR: Helm
  DEPLOY_PROJECT: projet_fastapi_deploy
  FF_SCRIPT_SECTIONS: "true"

  MANUAL_MODE: false  # Permettre le déclenchement manuel des jobs (utile en test)
  EXECUTION_MODE: "docker"  # docker / shell
  ENABLE_SAST: true


# # utlisation d'un Workflow pour ajuster les variables selon le type de Runner voulu
# workflow:
#   rules:
#     - if: '$EXECUTION_MODE == "docker"'
#       variables:
#         DOCKER_TLS_CERTDIR: "/certs"
#         DOCKER_TLS_VERIFY: "1"
#         DOCKER_CERT_PATH: "/certs/client"
#       when: always

#     - when: always


stages:
  - test        # Scan du code source (SAST)
  - build_push  # Build & Push child pipelines


.frontend_def:
  stage: build_push
  variables:
    # vérifie la valeur des variables et échoue si absentes. Vide ou "disabled" pour annuler le check.
    ENABLE_PRECHECK: false
    REQUIRED_VARS: "EXECUTION_MODE IMAGENAME TAG HOSTPORT CONTAINERPORT URL_PATH"
    IMAGENAME: frontend
    HOSTPORT: 6080
    CONTAINERPORT: 80
    URL_PATH: "/"

.backend_def:
  stage: build_push
  variables:
    # vérifie la valeur des variables et échoue si absente. Vide ou "disabled" pour annuler le check.
    ENABLE_PRECHECK: false
    REQUIRED_VARS: "EXECUTION_MODE IMAGENAME TAG HOSTPORT CONTAINERPORT URL_PATH"    
    IMAGENAME: backend
    HOSTPORT: 7800
    CONTAINERPORT: 8000
    URL_PATH: "/api/v1/utils/health-check/"


# ----------------------------------------------
# SAST code Scanning (requiert Docker Executor)
# ----------------------------------------------

semgrep-sast:
  stage: test
  rules:
    - if: '$EXECUTION_MODE == "docker" && $ENABLE_SAST == "true"'
  tags:
    - docker-executor


# --------------------------------------------------------------------------------------------
# OPTION 1 : Utiliser un Runner en mode Docker Executor
# --------------------------------------------------------------------------------------------

.job_rules_docker:
  rules:
    # déclencher si les fichiers du dossiers changent (matche aussi sur trigger, sans git diff)
    - if: '$EXECUTION_MODE == "docker"'
      changes:
        - $IMAGENAME/*
        - $IMAGENAME/**/*
    # fallback de déclenchement manuel si activé
    - if: '$EXECUTION_MODE == "docker" && $MANUAL_MODE =~ /^(1|true|yes)$/'
      when: manual
    # sinon, ne jamais déclencher
    - when: never
  trigger:
    include: ".gitlab/ci/templates/build-template-dind.yml"
    strategy: depend


# Trigger Build, Run, Push Frontend
frontend_build_dind:
  stage: build_push
  extends:
    - .job_rules_docker
    - .frontend_def


# Trigger Build, Run, Push Backend
backend_build_dind:
  stage: build_push
  extends:
    - .job_rules_docker
    - .backend_def


# --------------------------------------------------------------------------------------------
# OPTION 2 : Utiliser un Runner en mode Shell Executor
# --------------------------------------------------------------------------------------------

.job_rules_shell:
  rules:
    # déclencher si les fichiers du dossiers changent (matche aussi sur trigger, sans git diff)
    - if: '$EXECUTION_MODE == "shell"'
      changes:
        - $IMAGENAME/*
        - $IMAGENAME/**/*
    # fallback de déclenchement manuel si activé
    - if: '$EXECUTION_MODE == "shell" && $MANUAL_MODE =~ /^(1|true|yes)$/'
      when: manual
    # sinon, ne jamais déclencher
    - when: never
  trigger:
    include: ".gitlab/ci/templates/build-template-shell.yml"
    strategy: depend


# Trigger Build, Run, Push Frontend
frontend_build_shell:
  stage: build_push
  extends:
    - .job_rules_shell
    - .frontend_def


# Trigger Build, Run, Push Backend
backend_build_shell:
  stage: build_push
  extends:
    - .job_rules_shell
    - .backend_def


# --------------------------------------------------------------------------------------------
# Les images pushées sont ensuite detecteées par Kargo
# Kargo organise la configuration de deploiement et déclenche le pipeline
# --------------------------------------------------------------------------------------------
