# Modèle de pipeline de déploiement utilisant des jobs réutilisables
# Organise le déploiement dans les environnements : dev, qa, staging, prod

# Les variables suivantes doivent être définies par le pipeline appelant (ou son parent)
#
#   IMAGENAME:      nom de l'image Docker (et du dossier contenant le code source)
#   TAG:            tag de l'image Docker (par exemple, $CI_COMMIT_SHORT_SHA ou "latest")
#   NAMESPACE:      namespace Kubernetes (par exemple, dev, qa, staging, prod)
#   CHART_DIR:      repertoire contenant les fichiers du Chart Helm
#   DEPLOY_NAME:    nom de déploiment Helm (release name) du mciro-service
#   HOSTNAME:       nom d'hôte utilisé pour générer le FQDN du service (ex: api, dashboard, smtp)
#   DEPLOY_DOMAIN:  domaine utilisé pour accéder au service (ex: app.dev.mondomaine.com)
#   URL_PATH:       chemin URL pour accéder au service (ex: "api/v1/health")
#
#   ENV_NAME:       Nom de l'environnement (par exemple, dev/feature-branch, qa/main, staging/main, prod/main)
#                   Doit être unique pour chaque job de déploiement (surcharger le job dans l'appelant))

include:
  - local: '/ci-templates/.ci-var-precheck.yml'
  - local: '/ci-templates/.ci-deploy-jobs-templates.yml'

stages:
  - pre_checks
  - deploy
  # - test

deploy:
  environment:
    on_stop: stop_deploy
  variables:
    ENV_NAME: $ENV_NAME
  extends: .deploy_template

stop_deploy:
  extends: .stop_deploy_template
