.integration_test:
  script:
    # Vérifier que l'opération login fonctionne correctement sur la Gateway
    - curl -sfv -o /dev/null -w "HTTP Code':' %{http_code}\n" http://$VM_IP:$NODEPORT/docs
    - curl -sfv -o /dev/null -w "HTTP Code':' %{http_code}\n"  --header "Content-Type':' application/json" --request POST --data '{"username":"admin","password":"a"}' http://$VM_IP:$NODEPORT/api/login
  rules:
    - changes:
        - "users/**/*"
        - "orders/**/*"
        - "gateway/**/*"
      when: on_success
    - when: never