# ----------------------------------------------
# PRECHECKS des Varialbles
# Les passages de variables sont très aléatoires entre les différents niveaux de pipeline
# Il est donc important de vérifier que les variables nécessaires sont bien définies
# sinon, on arrête le pipeline immédiatement
# ----------------------------------------------

stages:
  - pre_checks

var_checks:
  stage: pre_checks
  script:
    - |
      REQUIRED_VARS=("IMAGENAME" "HOSTPORT" "TAG" "SERVICE_TYPE" "NODEPORT" "NODEPORT_DEV" "SVC_NODEPORT_DEV" "NODEPORT_QA" "SVC_NODEPORT_QA" "NODEPORT_STAGING" "SVC_NODEPORT_STAGING" "NODEPORT_PROD" "SVC_NODEPORT_PROD" "CHART_DIR" "DEPLOY_DOMAIN")
      for VAR in "${REQUIRED_VARS[@]}"; do
        if [ -z "${!VAR}" ]; then
          echo "Error: Environment variable '$VAR' is not set."
        else
          echo "Environment variable '$VAR' is set to '${!VAR}'."
        fi
      done